### ISSUE TITLE
Add New Jersey to geobtaa open data map

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/btaamap#5]

**Comment by karenmajewicz** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
```

**Comment by karenmajewicz** [comment]
- [x] add NJ to state GeoJson
- [x] Create new shapefile of all counties
- [x] Adjust attribute table to use same field names
- [x] export both state and county files to GeoJSON
- [x] Run geobtaa map with new geojsons
- [ ] publish updated map

**Comment by karenmajewicz** [comment]
Need to troubleshoot - the script produces a new states topoJson, but the application does not display it.
